### ISSUE TITLE
Recipe App Programming Project

### ISSUE THREAD

**Issue by Kanyorok** [Kanyorok/TastyTracks#10]
# [RoR group project: set up your Kanban board](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/setup_kanban_board.md#ror-group-project-set-up-your-kanban-board)

#### Project(Kanban Board) Link -  [Kanban Board](https://github.com/users/Kanyorok/projects/4)
* Team (Two Member Team):

Team Member 1: @Kanyorok 
Team Member 2: @lilskyex0x

**Comment by souad988** [comment]
Very well done @Kanyorok  @lilskyex0x , the kanban board includes cards for the given tasks in the requirements, each task has a proper title and description and is assigned to a team member 👍🏼 , One small thing is missing : 
**Required:**
- [ ] the In Review column please don't forget to add it as it helps you see if a PR needs to be reviewed.
**Optional:**
- [ ]  also please add a card specifying how has the task to setup the project and add dependencies.

**Comment by Strangeal** [comment]
Hi @Kanyorok 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/JoSiL3L4ON8DlyVxv0/giphy.gif)

## Highlights
- Added `In Review` column ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
